#!/bin/bash
# clawra-selfie.sh — Generate selfie via OpenRouter and send via Telegram
#
# Usage: ./clawra-selfie.sh "<context>" "<caption>" ["<mode>"]
#
# Environment variables required:
#   OPENROUTER_API_KEY   - OpenRouter API key
#   TELEGRAM_BOT_TOKEN   - Telegram bot token
#   TELEGRAM_CHAT_ID     - Target chat ID
#   SELFIE_MODEL         - Image model (default: google/gemini-2.5-flash-image)

set -euo pipefail

REFERENCE_IMAGE="https://imgix.ranker.com/user_node_img/50149/1002963598/original/1002963598-photo-u220763866"

USER_CONTEXT="${1:-}"
CAPTION="${2:-}"
MODE="${3:-auto}"
MODEL="${SELFIE_MODEL:-google/gemini-2.5-flash-image}"

if [ -z "$USER_CONTEXT" ]; then
    echo "Usage: $0 <context> [caption] [mode]"
    exit 1
fi

if [ -z "${OPENROUTER_API_KEY:-}" ]; then
    echo "Error: OPENROUTER_API_KEY not set"
    exit 1
fi

# Auto-detect mode
if [ "$MODE" = "auto" ]; then
    if echo "$USER_CONTEXT" | grep -qiE "outfit|wearing|clothes|dress|suit|fashion|full-body|mirror"; then
        MODE="mirror"
    elif echo "$USER_CONTEXT" | grep -qiE "cafe|restaurant|beach|park|city|close-up|portrait|face|eyes|smile"; then
        MODE="direct"
    else
        MODE="mirror"
    fi
fi

echo "[INFO] Mode: $MODE | Model: $MODEL"

# Build prompt
if [ "$MODE" = "direct" ]; then
    PROMPT="Edit this photo: create a close-up selfie of this exact same person at $USER_CONTEXT. Keep her exact face, hair, and features identical. She is taking the selfie herself with her phone, direct eye contact with the camera, looking straight into the lens, face fully visible. Photorealistic, natural lighting."
else
    PROMPT="Edit this photo: create a mirror selfie of this exact same person, but $USER_CONTEXT. Keep her exact face, hair, and features identical. She is taking a mirror selfie with her phone visible in the reflection. Photorealistic, natural lighting."
fi

echo "[INFO] Generating selfie via OpenRouter..."

# Use python3 for JSON construction and base64 decoding (stdlib only)
IMAGE_PATH="/tmp/jenni-selfie-$$.png"

export REFERENCE_IMAGE PROMPT MODEL IMAGE_PATH

python3 << 'PYEOF'
import json, base64, urllib.request, os, sys

ref = os.environ.get("REFERENCE_IMAGE", "https://imgix.ranker.com/user_node_img/50149/1002963598/original/1002963598-photo-u220763866")
prompt = os.environ["PROMPT"]
model = os.environ.get("MODEL", "google/gemini-2.5-flash-image")
api_key = os.environ["OPENROUTER_API_KEY"]
image_path = os.environ["IMAGE_PATH"]

body = json.dumps({
    "model": model,
    "messages": [{
        "role": "user",
        "content": [
            {"type": "text", "text": prompt},
            {"type": "image_url", "image_url": {"url": ref}}
        ]
    }]
}).encode()

req = urllib.request.Request(
    "https://openrouter.ai/api/v1/chat/completions",
    data=body,
    headers={
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
)

resp = json.loads(urllib.request.urlopen(req, timeout=120).read())

if "error" in resp:
    print(f"API error: {resp['error']}", file=sys.stderr)
    sys.exit(1)

images = resp.get("choices", [{}])[0].get("message", {}).get("images", [])
if not images:
    print("No image generated by model", file=sys.stderr)
    sys.exit(1)

data_uri = images[0]["image_url"]["url"]
b64_data = data_uri.split(",", 1)[1]
with open(image_path, "wb") as f:
    f.write(base64.b64decode(b64_data))

print(f"Image saved: {image_path} ({os.path.getsize(image_path)} bytes)")
PYEOF

echo "[INFO] Sending via Telegram..."

# Send via Telegram Bot API
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
    curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendPhoto" \
        -F "chat_id=$TELEGRAM_CHAT_ID" \
        -F "photo=@$IMAGE_PATH" \
        -F "caption=$CAPTION" > /dev/null
    echo "[INFO] Selfie sent via Telegram!"
else
    echo "[WARN] TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set"
    echo "[INFO] Image saved at: $IMAGE_PATH"
fi

echo ""
echo "--- Result ---"
echo "{\"success\": true, \"image_path\": \"$IMAGE_PATH\", \"mode\": \"$MODE\", \"model\": \"$MODEL\"}"
